accounts/urls.py
from django.urls import path
from . views import UserLogin, user_account, UserRegistration, EditProfile, UserProfile
from django.contrib.auth.views import *
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', EditProfile.as_view(), name='account'),  # требуется серьезная доработка
    path('profile/<str:username>', UserProfile.as_view(), name='user_profile'),  # ВАЖНО!!!

    path('login/', LoginView.as_view(
        template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='account/logout.html'), name='logout'),
    path('registration/', UserRegistration.as_view(), name='registration'),

    path('password/change/', PasswordChangeView.as_view(
        template_name='account/pass_change.html',
        success_url=reverse_lazy('accounts:password_change_done')),
        name='pass_change'),
    path('password/change/done', PasswordChangeDoneView.as_view(
        template_name='account/pass_done.html'), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [

    path('post/create/', views.PostCreate.as_view(), name='post_create_url'),

    path('post/edit/<slug:slug>', views.PostEdit.as_view(), name='post_edit_url'),
    path('post/delete/<slug:slug>', views.PostDelete.as_view(), name='post_delete_url'),

    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('account/<str:username>', views.post_list, name='post_list_by_user'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('search/', views.post_search, name='post_search'),
]

pycharm_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),

    path('myblog/', include('myblog.urls')),

]

blog/models.py
from taggit.managers import TaggableManager
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from time import time
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from random import randint


def make_slug(st):

    new_slug = slugify(st) + '-' + str(int(time())) + '-' + str(int(randint(0, 100)))
    return new_slug


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    """ Модель поста """

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', blank=True)
    body = RichTextUploadingField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager()        # tag

    objects = models.Manager()       # Менеджер обьектов по умолчанию
    published = PublishManager()    # Пользовательский менеджер обьектов

    class Meta:
        ordering = ('-publish',)

    def save(self, *args, **kwargs):
        if not self.id:
            self.status = 'published'
            self.slug = make_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):

    """ Модель комментария """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)  # В будущем надо будет убрать
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment', blank=True, null=True)
    email = models.EmailField()  # В будущем удалить
    body = models.TextField(max_length=15000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    activate = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class CommentRating(models.Model):

    """ Модель рейтинга комментария """

    # ip = models.CharField('IP', max_length=15)
    comment = models.OneToOneField(Comment, on_delete=models.CASCADE, related_name='comment_rating')
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.comment} - rating: {self.rating}"


class Images(models.Model):

    """ Модель изображения/изображений поста """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    title = models.CharField(max_length=150, blank=True)
    image = models.ImageField(upload_to='post_images/', blank=True)
    upload_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('upload_time',)

    def __str__(self):
        return 'Post: {}, Upload_time: {}, Title: {}'.format(self.post, self.upload_time, self.title)

blog/forms.py
from django import forms
from . models import Comment, Post, CommentRating
from ckeditor.widgets import CKEditorWidget


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {'user': forms.HiddenInput()}
        fields = ('body', 'user')


class CommentRatingForm(forms.ModelForm):

    post_rating = forms.IntegerField()

    class Meta:
        model = CommentRating
        fields = ('rating',)


class SearchForm(forms.Form):
    query = forms.CharField(widget=CKEditorWidget)


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        widgets = {'author': forms.HiddenInput()}
        fields = ['title', 'body', 'tags', 'author']

blog/views.py
from taggit.models import Tag
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, View
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm, PostForm, CommentRatingForm
from .models import Post, Comment, CommentRating
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponse

import logging


logger = logging.getLogger('blog_views')

# отображение списка статей


def post_list(request, tag_slug=None):

    object_list = Post.published.all()

    tag = None
    tags = Post.tags.all()

    paginate_number = 3

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, paginate_number)
    page = request.GET.get('page')

    logger.info('Отображение списка постов')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag, 'tags': tags})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_search(request):

    """ Функция поиска постов по содержанию тела поста, загаловку статьи и тегам"""

    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('tags__name') + SearchVector('title') + SearchVector('body')
            search_query = SearchQuery(query)
            # results = list(set(Post.objects.annotate(search=search_vector).filter(search=search_query)))
            results = list(set(Post.objects.annotate(search=search_vector).filter(search=search_query)))
            # results = list(set(Post.objects.annotate(rank=search_rank).order_by('-rank').\

    logger.info('Поиск постов')
    return render(request, 'blog/post/search.html', {'form_search': form, 'query': query, 'results': results})


def post_detail(request, year, month, day, post):

    """ Детальное отображение поста """

    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(activate=True)
    images = post.images.all()

    new_comment = None

    try:
        if request.method == 'POST':
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                comment_form = comment_form.save(commit=False)
                comment_form.post = post
                logger.info('Добавление комментария')
                comment_form.user = request.user
                comment_form.save()
        else:
            logger.info('Загрузка формы комментария')
            comment_form = CommentForm()
    except ValueError:
        return HttpResponse('Only authorized users can add comments', status=403)

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'images': images,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):

    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {} "'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'gitaglotus@gmail.com', [cd['to']])
            # send_mail(subject, message, 'admin@blog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


class PostCreate(View):

    """ Отвечает за создание поста """

    def get(self, request):
        logger.info('Отображение формы поста')
        post_form = PostForm(request.POST)
        return render(request, 'blog/create/post_create.html', {'post_form': post_form})

    def post(self, request):
        try:
            post_form = PostForm(request.POST)
            if post_form.is_valid():
                post_form.save(commit=False)
                post_form.instance.author = request.user
                post_form.save()
                logger.info('Cоздание поста')
                return render(request, 'blog/create/post_success_created.html')
        except ValueError:
            return HttpResponse('You don\'t have permissions make this', status=403)


class PostEdit(View):

    """ Отвечает за измение постов """

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        post_form = PostForm(instance=post)
        return render(request, 'blog/post/post_edit.html', {'post_form': post_form, 'post': post})

    def post(self, request, slug):

        post = Post.objects.get(slug=slug)
        post_form = PostForm(request.POST, instance=post)
        author = post.author

        if post_form.is_valid():
            if request.user == author or request.user.is_staff:
                post_form.save(commit=False)
                logger.info('Обновление поста')
                post_form.instance.author = author
                post_form.save()
                return redirect(post)
            else:
                return HttpResponse(status=403)
        return render(request, 'blog/post/post_edit.html', {'post_form': post_form, 'post': post})


class PostDelete(View):

    """ Отвечает за удаление поста """

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        if request.user == post.author or request.user.is_staff:
            return render(request, 'blog/post/post_delete.html', {'post': post})
        return redirect('blog:post_list')

    def post(self, request, slug):
        post = Post.objects.get(slug=slug)
        if request.user == post.author or request.user.is_staff:
            post.delete()
            return redirect('blog:post_list')
        else:
            return HttpResponse('You don\'t have permissions make this', status=403)

blog/templates/blog/includes/post_inner.html
{% load blog_tags %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish|date:"d.m.y" }} by <a href="{% url "accounts:user_profile" post.author %}">{{ post.author }}</a></p>
{{ post.body|markdown|truncatewords_html:125 }}
<img src="{{ post.images.image.url }} " alt="">

blog/templates/blog/includes/post_innter_detail.html
{% load blog_tags %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Published {{ post.publish|date:"d.m.y" }} by <a href="{% url "accounts:user_profile" post.author %}">{{ post.author }}</a></p>
{{ post.body|markdown}}
<img src="{{ post.images.image.url }} " alt="">

blog/templates/blog/includes/sidebar.html
{% extends "blog/base.html" %}
{% load blog_tags %}

blog/templates/blog/includes/top.html
<div class="topnav">
    <a class="active" href= "{% url "blog:post_list" %}">Home</a>
    <a href="#news">News</a>
    <a href="#contact">Contact</a>
    <a href="{% url 'blog:post_create_url' %}">Create post</a>
    {% if request.user.is_authenticated %}
        <a class="myacc" href="{% url "accounts:logout" %}">Logout</a>
        <a class="myacc" href="{% url "accounts:account" %}">My account</a>
        <a class="myacc">Hello, {{ request.user }}!</a>
    {% else %}
        <a class="myacc" href="{% url 'accounts:registration' %}">Registration</a>
        <a class="myacc" href="{% url "accounts:login" %}">Login</a>
    {% endif %}
</div>
{#<nav class="navbar navbar-expand-lg navbar-green bg-success">#}
{#  <a class="navbar-brand text-dark" href="#">Navbar</a>#}
{#  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#    <span class="navbar-toggler-icon"></span>#}
{#  </button>#}
{##}
{#  <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#    <ul class="navbar-nav mr-auto">#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link text-dark" href="#">Home <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link text-dark" href="#">Link</a>#}
{#      </li>#}
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#">Disabled</a>#}
{#      </li>#}
{#    </ul>#}
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0 text-dark"  type="submit">Search</button>#}
{#    </form>#}
{#  </div>#}
{#</nav>#}