accounts/urls.py
from django.urls import path
from . views import UserLogin, user_account, UserRegistration, EditProfile, UserProfile
from django.contrib.auth.views import *
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', EditProfile.as_view(), name='account'),  # требуется серьезная доработка
    path('profile/<str:username>', UserProfile.as_view(), name='user_profile'),  # ВАЖНО!!!

    path('login/', LoginView.as_view(
        template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='account/logout.html'), name='logout'),
    path('registration/', UserRegistration.as_view(), name='registration'),

    path('password/change/', PasswordChangeView.as_view(
        template_name='account/pass_change.html',
        success_url=reverse_lazy('accounts:password_change_done')),
        name='pass_change'),
    path('password/change/done', PasswordChangeDoneView.as_view(
        template_name='account/pass_done.html'), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [

    path('post/create/', views.PostCreate.as_view(), name='post_create_url'),

    path('post/edit/<slug:slug>', views.PostEdit.as_view(), name='post_edit_url'),
    path('post/delete/<slug:slug>', views.PostDelete.as_view(), name='post_delete_url'),

    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('account/<str:username>', views.post_list, name='post_list_by_user'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('search/', views.post_search, name='post_search'),
]

pycharm_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),

    path('myblog/', include('myblog.urls')),

]

blog/models.py
from taggit.managers import TaggableManager
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from time import time
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField
from random import randint


def make_slug(st):

    new_slug = slugify(st) + '-' + str(int(time())) + '-' + str(int(randint(0, 100)))
    return new_slug


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    """ Модель поста """

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish', unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', blank=True)
    body = RichTextUploadingField(blank=True, null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager()        # tag

    objects = models.Manager()       # Менеджер обьектов по умолчанию
    published = PublishManager()    # Пользовательский менеджер обьектов

    class Meta:
        ordering = ('-publish',)

    def save(self, *args, **kwargs):
        if not self.id:
            self.status = 'published'
            self.slug = make_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):

    """ Модель комментария """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)  # В будущем надо будет убрать
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment', blank=True, null=True)
    email = models.EmailField()  # В будущем удалить
    body = models.TextField(max_length=15000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    activate = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class CommentRating(models.Model):

    """ Модель рейтинга комментария """

    # ip = models.CharField('IP', max_length=15)
    comment = models.OneToOneField(Comment, on_delete=models.CASCADE, related_name='comment_rating')
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.comment} - rating: {self.rating}"


class Images(models.Model):

    """ Модель изображения/изображений поста """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    title = models.CharField(max_length=150, blank=True)
    image = models.ImageField(upload_to='post_images/', blank=True)
    upload_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('upload_time',)

    def __str__(self):
        return 'Post: {}, Upload_time: {}, Title: {}'.format(self.post, self.upload_time, self.title)

blog/forms.py
from django import forms
from . models import Comment, Post, CommentRating
from ckeditor.widgets import CKEditorWidget


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {'user': forms.HiddenInput()}
        fields = ('body', 'user')


class CommentRatingForm(forms.ModelForm):

    post_rating = forms.IntegerField()

    class Meta:
        model = CommentRating
        fields = ('rating',)


class SearchForm(forms.Form):
    query = forms.CharField(widget=CKEditorWidget)


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        widgets = {'author': forms.HiddenInput()}
        fields = ['title', 'body', 'tags', 'author']

blog/views.py
from taggit.models import Tag
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, View
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm, PostForm, CommentRatingForm
from .models import Post, Comment, CommentRating
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponse

import logging


logger = logging.getLogger('blog_views')

# отображение списка статей


def post_list(request, tag_slug=None):

    object_list = Post.published.all()

    tag = None
    tags = Post.tags.all()

    paginate_number = 3

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, paginate_number)
    page = request.GET.get('page')

    logger.info('Отображение списка постов')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag, 'tags': tags})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_search(request):

    """ Функция поиска постов по содержанию тела поста, загаловку статьи и тегам"""

    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('tags__name') + SearchVector('title') + SearchVector('body')
            search_query = SearchQuery(query)
            # results = list(set(Post.objects.annotate(search=search_vector).filter(search=search_query)))
            results = list(set(Post.objects.annotate(search=search_vector).filter(search=search_query)))
            # results = list(set(Post.objects.annotate(rank=search_rank).order_by('-rank').\

    logger.info('Поиск постов')
    return render(request, 'blog/post/search.html', {'form_search': form, 'query': query, 'results': results})


def post_detail(request, year, month, day, post):

    """ Детальное отображение поста """

    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(activate=True)
    images = post.images.all()

    new_comment = None

    try:
        if request.method == 'POST':
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                comment_form = comment_form.save(commit=False)
                comment_form.post = post
                logger.info('Добавление комментария')
                comment_form.user = request.user
                comment_form.save()
        else:
            logger.info('Загрузка формы комментария')
            comment_form = CommentForm()
    except ValueError:
        return HttpResponse('Only authorized users can add comments', status=403)

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'images': images,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):

    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {} "'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'gitaglotus@gmail.com', [cd['to']])
            # send_mail(subject, message, 'admin@blog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


class PostCreate(View):

    """ Отвечает за создание поста """

    def get(self, request):
        logger.info('Отображение формы поста')
        post_form = PostForm(request.POST)
        return render(request, 'blog/create/post_create.html', {'post_form': post_form})

    def post(self, request):
        try:
            post_form = PostForm(request.POST)
            if post_form.is_valid():
                post_form.save(commit=False)
                post_form.instance.author = request.user
                post_form.save()
                logger.info('Cоздание поста')
                return render(request, 'blog/create/post_success_created.html')
        except ValueError:
            return HttpResponse('You don\'t have permissions make this', status=403)


class PostEdit(View):

    """ Отвечает за измение постов """

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        post_form = PostForm(instance=post)
        return render(request, 'blog/post/post_edit.html', {'post_form': post_form, 'post': post})

    def post(self, request, slug):

        post = Post.objects.get(slug=slug)
        post_form = PostForm(request.POST, instance=post)
        author = post.author

        if post_form.is_valid():
            if request.user == author or request.user.is_staff:
                post_form.save(commit=False)
                logger.info('Обновление поста')
                post_form.instance.author = author
                post_form.save()
                return redirect(post)
            else:
                return HttpResponse(status=403)
        return render(request, 'blog/post/post_edit.html', {'post_form': post_form, 'post': post})


class PostDelete(View):

    """ Отвечает за удаление поста """

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        if request.user == post.author or request.user.is_staff:
            return render(request, 'blog/post/post_delete.html', {'post': post})
        return redirect('blog:post_list')

    def post(self, request, slug):
        post = Post.objects.get(slug=slug)
        if request.user == post.author or request.user.is_staff:
            post.delete()
            return redirect('blog:post_list')
        else:
            return HttpResponse('You don\'t have permissions make this', status=403)

blog/templates/blog/post/all_tags.html
<ul>
{% for tag in tags %}
    <li>
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
    </a>
    </li>
{% endfor %}
</ul>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}

{% block content %}

    {% include 'blog/includes/post_innter_detail.html' %}

    {% if post.author == request.user or request.user.is_staff == True%}
        <p>
            <a href="{% url "blog:post_edit_url" slug=post.slug %}">
            Edit
            </a>
            <a href="{% url "blog:post_delete_url" slug=post.slug %}">
               Delete
            </a>
        </p>
    {% endif %}

    {#  Похожие посты  #}

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {#  Комментарии  #}

    {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {%for comment in comments %}
        <div class="comment">
            <p class="info">
            Comment {{ forloop.counter }} by {{ comment.user }}
            {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}

            {#  Рейтинг комментария  #}

{#            <p>Rating: {{ comment.comment_rating.rating }}</p>#}
{#            {% if request.user.is_authenticated %}#}
{#                <form action="{% url '.' comment.pk %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    <input type="submit" name = '+' value="{{ post_rating }}">#}
{#                    <input type="submit" name = '-' value="-">#}
{#                </form>#}
{#                {% else %}#}
{#                    <p>Only authorized users can change the rating of a comment</p>#}
{#            {% endif %}#}
        </div>
    {% empty %}
        <p>No comments</p>
    {% endfor %}

    {#  Добавление комментария  #}
    <h2>New Comment</h2>
     {% if request.user.is_authenticated %}
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
            <h3><a href= {{ post.get_absolute_url }}> If you want add new comment click here</a></h3>
        {% else %}
            <h2>Add a new comment</h2>
            <form method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
         {% else %}
         <h2>Only authorized users can add comments, you can <a href="{% url 'accounts:login' %}">log-in</a></h2>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% empty %}
    <p>No posts</p>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Posts{% endblock %}

{% block content %}
  <h1>Posts</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
      {% include 'blog/includes/post_inner.html' %}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/post_delete.html
{% extends 'global_base.html' %}

{% block title %}Delete post{% endblock %}


{% block content %}
    {% if post.author == request.user or request.user.is_staff == True%}
        <h1>Delete post {{ post.title }}</h1>
        <h3>If you really want to delete it click the button</h3>
        <form action="{% url 'blog:post_delete_url' slug=post.slug%}" method="post">
            {% csrf_token %}
            <input type="submit" value="delete">
        </form>
    {% else %}
        <h1>Not enough rights</h1>
        <h3>You are not part of the development team or the creator of the post.</h3>
    {% endif %}
{% endblock %}

blog/templates/blog/post/post_edit.html
{% extends 'global_base.html' %}
{% load blog_tags %}

{% block title %} Post edit {% endblock %}

{% block content %}
    {% if request.user.is_authenticated and post.author == request.user or request.user.is_staff == True%}
        <form action="{% url 'blog:post_edit_url' slug=post.slug %}" method="post">
            {% csrf_token %}
{#            {{ post_form.as_p | markdown }}#}
            {{ post_form.media }}
            <h2>Title</h2>
            {{ post_form.title }}<br><br>
            <h2>Body</h2>
            {{ post_form.body|safe }}<br>
            <h2>Tags</h2>
            {{ post_form.tags }}<br>
            <input type="submit" value="update">
        </form>
    {% else %}
        <p>You have not permissions edit this post</p>
    {% endif %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </h3>
    {% for post in results %}
{#        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>#}
           {% include 'blog/includes/post_inner.html' %}
{#        {{ post.body|markdown|truncatewords:5 }}<br><br>#}
    {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
        {{ form_search.as_p }}
        <input type="submit" value="Search">
    </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
{% endblock %}