accounts/urls.py
from django.urls import path
from . views import UserLogin, user_account, UserRegistration, EditProfile, UserProfile
from django.contrib.auth.views import *
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', EditProfile.as_view(), name='account'),  # требуется серьезная доработка
    path('profile/<str:username>', UserProfile.as_view(), name='user_profile'),  # ВАЖНО!!!

    path('login/', LoginView.as_view(
        template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='account/logout.html'), name='logout'),
    path('registration/', UserRegistration.as_view(), name='registration'),

    path('password/change/', PasswordChangeView.as_view(
        template_name='account/pass_change.html',
        success_url=reverse_lazy('accounts:password_change_done')),
        name='pass_change'),
    path('password/change/done', PasswordChangeDoneView.as_view(
        template_name='account/pass_done.html'), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from .feeds import LatestPostsFeed
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [

    path('post/create/', views.PostCreate.as_view(), name='post_create_url'),

    path('post/edit/<slug:slug>', views.PostEdit.as_view(), name='post_edit_url'),
    path('post/delete/<slug:slug>', views.PostDelete.as_view(), name='post_delete_url'),

    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('account/<str:username>', views.post_list, name='post_list_by_user'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),

    path('search/', views.post_search, name='post_search'),
]

pycharm_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls')),

    path('myblog/', include('myblog.urls')),

]

templates/global_base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
{#<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">#}
</head>
<body>
    {% include "blog/includes/top.html" %}
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            {% endfor %}
        </ul>
    {% endif %}
{#    {% include 'blog/includes/sidebar.html' %}#}


{#               SIDEBAR               #}


    <div id="sidebar">
        <h1><a href="{% url "blog:post_list" %}">Main page</a></h1>

        {#    DEV     #}

        <h4>Total posts: {% total_posts %}</h4>
        <h4>Total users: {% total_users %}</h4>

        <h4>Search field</h4>
        <ul>
            <form action="{% url 'blog:post_search'%}" method='get'>
                <input name = 'query' type="text" class="side_text" placeholder="Enter search text">
                <input type="submit" value="Search">
            </form>
        </ul>
        <br><br><br><br>
        {% if user_form %}
            <br>
            <h2>You can:</h2>
            <ul>
                <li><a href="{% url "accounts:pass_change" %}">change password</a></li>
                <li><a href="#">change username and profile settings</a></li>
            </ul>
        {% else %}
            <h4>Latest posts:</h4>
            {% show_latest_posts 3 %}
            {% if post.tags %}
                <h4>Tags in current post:</h4>
            {% else %}
                <h4>Tags:</h4>
            {% endif %}
            {% if post.tags %}
                <!-- post.tags.all-->
                <ul>
                {% for tag in post.tags.all%}
                    <li>
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                {% all_tags %}
            {% endif %}
        {% endif %}
{#        <h4>Search field</h4>#}
{#        <ul>#}
{#        <form action="{% url 'blog:post_search'%}" method='get'>#}
{#            <input name = 'query' type="text" class="side_text" placeholder="Enter search text">#}
{#            <input type="submit" value="Search">#}
{#        </form>#}
{#        </ul>#}
{#        <br><br>#}

    </div>
</body>
</html>